package dagjose

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	"github.com/ipld/go-ipld-prime/datamodel"
)

var _ datamodel.Node = nil // suppress errors when this dependency is not referenced
// Type is a struct embeding a NodePrototype/Type for every Node implementation in this package.
// One of its major uses is to start the construction of a value.
// You can use it like this:
//
// 		dagjose.Type.YourTypeName.NewBuilder().BeginMap() //...
//
// and:
//
// 		dagjose.Type.OtherTypeName.NewBuilder().AssignString("x") // ...
//
var Type typeSlab

type typeSlab struct {
	Bytes            _Bytes__Prototype
	Bytes__Repr      _Bytes__ReprPrototype
	JOSE             _JOSE__Prototype
	JOSE__Repr       _JOSE__ReprPrototype
	Recipient        _Recipient__Prototype
	Recipient__Repr  _Recipient__ReprPrototype
	Recipients       _Recipients__Prototype
	Recipients__Repr _Recipients__ReprPrototype
	Signature        _Signature__Prototype
	Signature__Repr  _Signature__ReprPrototype
	Signatures       _Signatures__Prototype
	Signatures__Repr _Signatures__ReprPrototype
	String           _String__Prototype
	String__Repr     _String__ReprPrototype
}

// --- type definitions follow ---

// Bytes matches the IPLD Schema type "Bytes".  It has bytes kind.
type Bytes = *_Bytes
type _Bytes struct{ x []byte }

// JOSE matches the IPLD Schema type "JOSE".  It has struct type-kind, and may be interrogated like map kind.
type JOSE = *_JOSE
type _JOSE struct {
	aad        _Bytes__Maybe
	ciphertext _Bytes__Maybe
	iv         _Bytes__Maybe
	payload    _Bytes__Maybe
	protected  _Bytes__Maybe
	recipients _Recipients__Maybe
	signatures _Signatures__Maybe
	tag        _Bytes__Maybe
}

// Recipient matches the IPLD Schema type "Recipient".  It has struct type-kind, and may be interrogated like map kind.
type Recipient = *_Recipient
type _Recipient struct {
	encrypted_key _Bytes__Maybe
}

// Recipients matches the IPLD Schema type "Recipients".  It has list kind.
type Recipients = *_Recipients
type _Recipients struct {
	x []_Recipient
}

// Signature matches the IPLD Schema type "Signature".  It has struct type-kind, and may be interrogated like map kind.
type Signature = *_Signature
type _Signature struct {
	protected _Bytes__Maybe
	signature _Bytes
}

// Signatures matches the IPLD Schema type "Signatures".  It has list kind.
type Signatures = *_Signatures
type _Signatures struct {
	x []_Signature
}

// String matches the IPLD Schema type "String".  It has string kind.
type String = *_String
type _String struct{ x string }
